server:
  port: 8081 #default port where the service will be started

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

management:
  security:
    enabled: false #disable the spring security on the management endpoints like /env, /refresh etc.

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.profiles: docker

server.port: 8080
