version: "2.1"

services:
  customer-service:
    build: microservices/customer-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  loan-application-service:
    build: microservices/loan-application-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: spring-cloud/eureka
    mem_limit: 350m

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    mem_limit: 350m
    ports:
      - "8443:8443"
      
  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/authorization-server
    mem_limit: 350m
