version: "2.1"

services:
  customer-service:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: microservices/customer-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  loan-application-service:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: microservices/loan-application-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  eureka:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/eureka
    mem_limit: 350m

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    mem_limit: 350m
    ports:
      - "8443:8443"
      
  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/authorization-server
    mem_limit: 350m

    
  config-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
    volumes:
      - $PWD/config-repo:/config-repo
    build: spring-cloud/config-server
    mem_limit: 350m
